

const initialBulls = [
  {
    id: 1,
    name: "Champion Wagyu Bull",
    breed: "Wagyu",
    reg: "WG123456",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.80397891-1a9a-4ee1-9f7c-d4f304256098.png",
    age: 4,
    weight: 750,
    semenStraws: 200,
    healthStatus: "Healthy",
    notes: "Superior marbling genetics with proven pedigree.",
  },
  {
    id: 2,
    name: "Elite Angus Bull",
    breed: "Angus",
    reg: "AG234567",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.c74f7f1f-481b-4292-a30a-f19de826e740.png",
    age: 5,
    weight: 800,
    semenStraws: 180,
    healthStatus: "Healthy",
    notes: "High fertility rates and consistent performance.",
  },
  {
    id: 3,
    name: "Premium Sahiwal Bull",
    breed: "Sahiwal",
    reg: "SW345678",
    status: "Inactive",
    image: "https://copilot.microsoft.com/th/id/BCO.fc49d174-2cba-4412-a939-1b06f993a1ba.png",
    age: 6,
    weight: 650,
    semenStraws: 150,
    healthStatus: "Injured",
    notes: "Strong adaptability and reliable milk genetics.",
  },
  {
    id: 4,
    name: "Holstein Friesian",
    breed: "Holstein",
    reg: "HF456789",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.b8c124be-3d2a-4e62-a7f3-f913b679299f.png",
    age: 4,
    weight: 720,
    semenStraws: 220,
    healthStatus: "Healthy",
    notes: "Excellent milk yield and superior dairy genetics.",
  },
  {
    id: 5,
    name: "Red Sindhi Bull",
    breed: "Sindhi",
    reg: "RS567990",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.8a141874-674f-469b-99ad-475ec5dff4b8.png",
    age: 7,
    weight: 680,
    semenStraws: 100,
    healthStatus: "Healthy",
    notes: "Renowned for resilience and fertility performance.",
  },
  {
    id: 6,
    name: "Brahman Bull",
    breed: "Brahman",
    reg: "BR234111",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.bdf84f43-f3d8-4a29-8184-b1723e19d461.png",
    age: 5,
    weight: 770,
    semenStraws: 160,
    healthStatus: "Healthy",
    notes: "Heat-tolerant and resilient, ideal for tropical climates.",
  },
  {
    id: 7,
    name: "Charolais Bull",
    breed: "Charolais",
    reg: "CH456222",
    status: "Inactive",
    image: "https://copilot.microsoft.com/th/id/BCO.6b25b2be-e826-44a1-9b30-b958cc8af722.png",
    age: 6,
    weight: 850,
    semenStraws: 140,
    healthStatus: "Sick",
    notes: "Known for rapid growth, heavy muscling, and beef quality.",
  },
  {
    id: 8,
    name: "Hereford Bull",
    breed: "Hereford",
    reg: "HF789333",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.016aa7b0-6c0a-4f6b-a1a1-322302845993.png",
    age: 5,
    weight: 700,
    semenStraws: 170,
    healthStatus: "Healthy",
    notes: "Hardy and adaptable with excellent meat yield.",
  },
  {
    id: 9,
    name: "Belgian Blue Bull",
    breed: "Belgian Blue",
    reg: "BB112233",
    status: "Active",
    image: "https://copilot.microsoft.com/th/id/BCO.c253a7cc-d7cd-48b0-9644-c9a38c2ccf23.png",
    age: 4,
    weight: 900,
    semenStraws: 210,
    healthStatus: "Healthy",
    notes: "Famous for double-muscling and high lean meat percentage.",
  },
  {
    id: 10,
    name: "Nili-Ravi Bull",
    breed: "Nili-Ravi",
    reg: "NR445566",
    status: "Inactive",
    image: "https://copilot.microsoft.com/th/id/BCO.1a276348-d565-4260-9808-49931878bae7.png",
    age: 8,
    weight: 680,
    semenStraws: 130,
    healthStatus: "Old Age",
    notes: "Renowned Pakistani breed for both milk and breeding strength.",
  },
];


export default initialBulls;